---
swagger: "2.0"
info:
  description: "This is an app to manage project by student or supervisor."
  version: "0.0.1-SNAPSHOT"
  title: "Project Management"
  contact:
    email: "phendzel.mail@gmail.com"
schemes:
- "http"
paths:
  /projects-api/user-details:
    get:
      tags:
      - "UserDetail"
      summary: "It is endpoint to test swagger contract"
      operationId: "getHelloWorld"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          schema:
            type: "string"
      security:
      - petstore_auth:
        - "read:pets"
  /users-api/users:
      get:
        tags:
        - "User"
        summary: "It is endpoint to test swagger contract #2"
        operationId: "getHelloWorld2"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            schema:
              type: "string"
        security:
        - petstore_auth:
          - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/api/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"